name: Python Package CI

on: [push, pull_request]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Add conda to system path
      run: echo $CONDA/bin >> $GITHUB_PATH

    - name: Install ffmpeg (system package)
      run: sudo apt-get update && sudo apt-get install -y ffmpeg

    # Primo tentativo: Conda
    - name: Install dependencies with conda
      id: conda-deps
      continue-on-error: true
      run: conda env update --file environment.yml --name base

    # Fallback: pip se conda fallisce o manca environment.yml
    - name: Install dependencies with pip
      if: steps.conda-deps.outcome == 'failure'
      run: pip install -r requirements.txt

    - name: Lint with flake8
      run: flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Test with pytest
      run: |
        export PYTHONPATH=$PYTHONPATH:$(pwd)
        pytest tests/
